on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3 # consulta actions
      - id: foo # identificação da ação para outputs
        uses: cadu1982/hello-action@v1 # referencia a action a ser usada
        with:
          who-to-greet: 'Carlos Ponce' # envia para inputs da action
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
      # recebe o value da action em outputs-> random-number -> value 
        shell: bash
      
