on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3 # consulta actions
      - id: key-four # identificação da ação para outputs
        uses: cadu1982/hello-action@v1 # referencia a action a ser usada
        with:
          key-one: 'Carlos Ponce' # envia para inputs da action
      - run: echo random-number ${{ steps.key-four.outputs.key-three }}
      # recebe o value da action em outputs-> random-number -> value 
        shell: bash